---
version: '3'
services:
  postgres-isaac:
    container_name: postgres-isaac
    image: postgres:10.11
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-employee_management_system}
      PGDATA: /data/postgres
    volumes:
        - postgres:/data/postgres
    ports:
      - "5432:5432"
    command: 
      - "postgres"
      - "-c"
      - "wal_level=logical"
    restart: unless-stopped

volumes:
  postgres: